/**
 * @fileoverview Schema definitions and validation helpers for the
 * `mood_logs` Firestore collection.
 *
 * Each document tracks a user's mood and energy level for a given date.
 *
 * Document ID: auto-generated by Firestore
 *
 * Collection: mood_logs
 *
 * Query patterns:
 * - By userId + date range: getMoodLogsByUserAndDate(db, userId, startDate, endDate)
 *   Requires composite index on (userId ASC, date DESC)
 */

const { FieldValue } = require("firebase-admin/firestore");

// ---------------------------------------------------------------------------
// Field metadata
// ---------------------------------------------------------------------------

/** @type {Object<string, {type: string, required: boolean, description: string, validate?: Function}>} */
const MOOD_LOG_FIELDS = {
  userId: {
    type: "string",
    required: true,
    description: "Telegram user ID (stringified)",
    validate: (v) => typeof v === "string" && v.length > 0,
  },
  date: {
    type: "string",
    required: true,
    description: "Date in ISO 8601 format (YYYY-MM-DD)",
    validate: (v) =>
      typeof v === "string" && /^\d{4}-\d{2}-\d{2}$/.test(v),
  },
  mood: {
    type: "number",
    required: true,
    description: "Mood rating (1–5, 1 = very bad, 5 = excellent)",
    validate: (v) => typeof v === "number" && Number.isInteger(v) && v >= 1 && v <= 5,
  },
  energy: {
    type: "number",
    required: true,
    description: "Energy level (1–5, 1 = very low, 5 = very high)",
    validate: (v) => typeof v === "number" && Number.isInteger(v) && v >= 1 && v <= 5,
  },
  note: {
    type: "string",
    required: false,
    description: "Optional note about the mood/energy state",
    validate: (v) => typeof v === "string",
  },
  createdAt: {
    type: "Timestamp",
    required: true,
    nullable: true,
    description:
      "Time of document creation (Firestore serverTimestamp; null before write)",
  },
};

// ---------------------------------------------------------------------------
// Collection name
// ---------------------------------------------------------------------------

const MOOD_LOGS_COLLECTION = "mood_logs";

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

/**
 * Validates a mood_log document against the schema.
 *
 * @param {Object} doc - The document data to validate
 * @returns {{ valid: boolean, errors: string[] }}
 *   `valid` is true when all required fields pass.
 *   `errors` contains human-readable messages for each violation.
 */
function validateMoodLog(doc) {
  const errors = [];

  if (!doc || typeof doc !== "object") {
    return { valid: false, errors: ["Document must be a non-null object"] };
  }

  for (const [fieldName, meta] of Object.entries(MOOD_LOG_FIELDS)) {
    const value = doc[fieldName];

    // Check required
    if (meta.required && value === undefined) {
      errors.push(`Missing required field: "${fieldName}"`);
      continue;
    }

    // Skip further checks if value is not present
    if (value === undefined) {
      continue;
    }
    if (value === null && meta.nullable) {
      continue;
    }
    if (value === null) {
      errors.push(`Missing required field: "${fieldName}"`);
      continue;
    }

    // Type check + optional custom validation
    if (meta.validate) {
      if (!meta.validate(value)) {
        errors.push(
          `Invalid value for field "${fieldName}": ${JSON.stringify(value)}`,
        );
      }
    }
  }

  return { valid: errors.length === 0, errors };
}

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

/**
 * Creates a validated mood_log document object ready for Firestore write.
 *
 * @param {Object} params
 * @param {string} params.userId - Telegram user ID
 * @param {string} params.date - ISO 8601 date string (YYYY-MM-DD)
 * @param {number} params.mood - Mood rating (1–5)
 * @param {number} params.energy - Energy level (1–5)
 * @param {string} [params.note] - Optional note
 * @returns {Object} Document data with createdAt set to FieldValue.serverTimestamp()
 * @throws {Error} If validation fails
 */
function createMoodLog({ userId, date, mood, energy, note }) {
  const doc = {
    userId,
    date,
    mood,
    energy,
    note: note || "",
    createdAt: FieldValue.serverTimestamp(),
  };

  const { valid, errors } = validateMoodLog(doc);
  if (!valid) {
    throw new Error(`Mood log validation failed: ${errors.join("; ")}`);
  }

  return doc;
}

// ---------------------------------------------------------------------------
// Query helpers
// ---------------------------------------------------------------------------

/**
 * Queries mood_logs for a specific user within a date range, ordered by
 * date descending.
 *
 * Requires a composite index on `mood_logs`:
 *   fields: userId ASC, date DESC
 *
 * @param {import("firebase-admin/firestore").Firestore} db - Firestore instance
 * @param {string} userId - Telegram user ID
 * @param {string} startDate - Start date (ISO 8601, inclusive)
 * @param {string} endDate - End date (ISO 8601, inclusive)
 * @returns {Promise<import("firebase-admin/firestore").DocumentData[]>}
 */
async function getMoodLogsByUserAndDate(db, userId, startDate, endDate) {
  const snapshot = await db
    .collection(MOOD_LOGS_COLLECTION)
    .where("userId", "==", userId)
    .where("date", ">=", startDate)
    .where("date", "<=", endDate)
    .orderBy("date", "desc")
    .get();

  const docs = [];
  snapshot.forEach((doc) => {
    docs.push({ id: doc.id, ...doc.data() });
  });
  return docs;
}

module.exports = {
  MOOD_LOGS_COLLECTION,
  MOOD_LOG_FIELDS,
  validateMoodLog,
  createMoodLog,
  getMoodLogsByUserAndDate,
};