/**
 * @fileoverview Schema definitions and validation helpers for the
 * `nutrition_logs` Firestore collection.
 *
 * Each document tracks a user's meal, vitamins, and water intake for a
 * given date and meal type.
 *
 * Document ID: auto-generated by Firestore
 *
 * Collection: nutrition_logs
 *
 * Query patterns:
 * - By userId + date range: getNutritionLogsByUserAndDate(db, userId, startDate, endDate)
 *   Requires composite index on (userId ASC, date DESC)
 */

const { FieldValue } = require('firebase-admin/firestore');

// ---------------------------------------------------------------------------
// Valid meal types
// ---------------------------------------------------------------------------

const VALID_MEAL_TYPES = ['breakfast', 'lunch', 'dinner', 'snack'];

// ---------------------------------------------------------------------------
// Field metadata
// ---------------------------------------------------------------------------

/** @type {Object<string, {type: string, required: boolean, description: string, validate?: Function}>} */
const NUTRITION_LOG_FIELDS = {
  userId: {
    type: 'string',
    required: true,
    description: 'Telegram user ID (stringified)',
    validate: (v) => typeof v === 'string' && v.length > 0,
  },
  date: {
    type: 'string',
    required: true,
    description: 'Date in ISO 8601 format (YYYY-MM-DD)',
    validate: (v) =>
      typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v),
  },
  mealType: {
    type: 'string',
    required: true,
    description: "Type of meal: 'breakfast', 'lunch', 'dinner', or 'snack'",
    validate: (v) =>
      typeof v === 'string' && VALID_MEAL_TYPES.includes(v),
  },
  foods: {
    type: 'array',
    required: true,
    description: 'List of food items consumed (at least 1 entry)',
    validate: (v) =>
      Array.isArray(v) &&
      v.length >= 1 &&
      v.every((item) => typeof item === 'string' && item.length > 0),
  },
  vitamins: {
    type: 'array',
    required: false,
    description: 'List of vitamins taken',
    validate: (v) =>
      Array.isArray(v) &&
      v.every((item) => typeof item === 'string'),
  },
  waterGlasses: {
    type: 'number',
    required: true,
    description: 'Number of glasses of water consumed (≥0)',
    validate: (v) =>
      typeof v === 'number' && Number.isInteger(v) && v >= 0,
  },
  createdAt: {
    type: 'Timestamp',
    required: true,
    nullable: true,
    description:
      'Time of document creation (Firestore serverTimestamp; null before write)',
  },
};

// ---------------------------------------------------------------------------
// Collection name
// ---------------------------------------------------------------------------

const NUTRITION_LOGS_COLLECTION = 'nutrition_logs';

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

/**
 * Validates a nutrition_log document against the schema.
 *
 * @param {Object} doc - The document data to validate
 * @returns {{ valid: boolean, errors: string[] }}
 *   `valid` is true when all required fields pass.
 *   `errors` contains human-readable messages for each violation.
 */
function validateNutritionLog(doc) {
  const errors = [];

  if (!doc || typeof doc !== 'object') {
    return { valid: false, errors: ['Document must be a non-null object'] };
  }

  for (const [fieldName, meta] of Object.entries(NUTRITION_LOG_FIELDS)) {
    const value = doc[fieldName];

    // Check required
    if (meta.required && value === undefined) {
      errors.push(`Missing required field: "${fieldName}"`);
      continue;
    }

    // Skip further checks if value is not present
    if (value === undefined) {
      continue;
    }
    if (value === null && meta.nullable) {
      continue;
    }
    if (value === null) {
      errors.push(`Missing required field: "${fieldName}"`);
      continue;
    }

    // Type check + optional custom validation
    if (meta.validate) {
      if (!meta.validate(value)) {
        errors.push(
          `Invalid value for field "${fieldName}": ${JSON.stringify(value)}`,
        );
      }
    }
  }

  return { valid: errors.length === 0, errors };
}

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

/**
 * Creates a validated nutrition_log document object ready for Firestore write.
 *
 * @param {Object} params
 * @param {string} params.userId - Telegram user ID
 * @param {string} params.date - ISO 8601 date string (YYYY-MM-DD)
 * @param {string} params.mealType - Type of meal ('breakfast' | 'lunch' | 'dinner' | 'snack')
 * @param {string[]} params.foods - List of food items (at least 1)
 * @param {string[]} [params.vitamins] - Optional list of vitamins taken
 * @param {number} [params.waterGlasses] - Number of glasses of water (≥0, default 0)
 * @returns {Object} Document data with createdAt set to FieldValue.serverTimestamp()
 * @throws {Error} If validation fails
 */
function createNutritionLog({ userId, date, mealType, foods, vitamins, waterGlasses }) {
  const doc = {
    userId,
    date,
    mealType,
    foods,
    vitamins: vitamins || [],
    waterGlasses: waterGlasses != null ? waterGlasses : 0,
    createdAt: FieldValue.serverTimestamp(),
  };

  const { valid, errors } = validateNutritionLog(doc);
  if (!valid) {
    throw new Error(`Nutrition log validation failed: ${errors.join('; ')}`);
  }

  return doc;
}

// ---------------------------------------------------------------------------
// Query helpers
// ---------------------------------------------------------------------------

/**
 * Queries nutrition_logs for a specific user within a date range, ordered by
 * date descending.
 *
 * Requires a composite index on `nutrition_logs`:
 *   fields: userId ASC, date DESC
 *
 * @param {import("firebase-admin/firestore").Firestore} db - Firestore instance
 * @param {string} userId - Telegram user ID
 * @param {string} startDate - Start date (ISO 8601, inclusive)
 * @param {string} endDate - End date (ISO 8601, inclusive)
 * @returns {Promise<import("firebase-admin/firestore").DocumentData[]>}
 */
async function getNutritionLogsByUserAndDate(db, userId, startDate, endDate) {
  const snapshot = await db
    .collection(NUTRITION_LOGS_COLLECTION)
    .where('userId', '==', userId)
    .where('date', '>=', startDate)
    .where('date', '<=', endDate)
    .orderBy('date', 'desc')
    .get();

  const docs = [];
  snapshot.forEach((doc) => {
    docs.push({ id: doc.id, ...doc.data() });
  });
  return docs;
}

module.exports = {
  NUTRITION_LOGS_COLLECTION,
  NUTRITION_LOG_FIELDS,
  VALID_MEAL_TYPES,
  validateNutritionLog,
  createNutritionLog,
  getNutritionLogsByUserAndDate,
};